apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: boardgames
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: boardgames-dev-db
        property: user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: boardgames-dev-db
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: boardgames-dev-db
        property: dbname
    - secretKey: DATABASE_URL
      remoteRef:
        key: boardgames-dev-db
        property: url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-credentials
  namespace: boardgames
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: app-credentials
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: boardgames-dev-app
        property: secret_key
