apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: boardgames
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::595324333130:role/boardgames-dev-irsa-role
