apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  namespace: boardgames
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
