name: Auto-assign PR author

on:
  pull_request:
    types: [ opened ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign PR author
      uses: actions-ecosystem/action-add-assignees@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ github.actor }}
