name: Security Scan

on:
  push:
    branches:
    - "main"
    - "develop"

  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install Gitleaks
      run: |
        GITLEAKS_VERSION="8.30.0"
        GITLEAKS_URL="https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
        curl -sSLf ${GITLEAKS_URL} | tar -xz -C /tmp gitleaks
        mv /tmp/gitleaks /usr/local/bin/

    - name: Run Gitleaks
      run: gitleaks git . --report-format json --report-path /tmp/gitleaks_report.json --verbose --redact --exit-code 1

    - name: Upload Gitleaks report
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: gitleaks_report
        path: /tmp/gitleaks_report.json
        retention-days: 7

  code_security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run Bandit
      run: bandit -r app/backend -ll -f json -o /tmp/bandit_report.json

    - name: Check dependencies for vulnerabilities
      run: |
        pip-audit -r requirements.txt -f json \
        | jq . \
        > /tmp/pip_audit_report.json
        pip-audit -r requirements-dev.txt -f json \
        | jq . \
        > /tmp/pip_audit_dev_report.json

    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: security_reports
        path: /tmp/*_report.json
        retention-days: 7
