name: Terraform Dev Environment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action to perform"
        required: true
        default: "plan"
        type: choice
        options:
        - "plan"
        - "apply"
        - "destroy"
      confirm_destroy:
        description: "Confirm destruction of resources (only used when action is 'destroy')"
        required: false
        default: "false"
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  terraform-env-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform/environments/dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.14.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ vars.AWS_PLATFORM_ROLE_ARN }}
        aws-region: eu-central-1

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      if: ${{ github.event.inputs.action != 'destroy' }}
      run: terraform plan -out=tfplan.binary

    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -auto-approve tfplan.binary

    - name: Terraform Plan Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform plan -destroy

    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' && github.event.inputs.confirm_destroy == 'true' }}
      run: terraform destroy -auto-approve
